#!/bin/bash
# board_conf.sh — shell loader for /var/lib/inno-pilot/board.conf
#
# Source this from other shell scripts to pull the detected Arduino board
# parameters into the calling shell:
#
#   source /path/to/board_conf.sh
#   load_board_conf            # exits 1 if the file is missing or incomplete
#   echo "$INNO_BOARD_FQBN"    # e.g. arduino:avr:nano
#   echo "$INNO_BOARD_PORT"    # e.g. /dev/ttyUSB0
#   echo "$INNO_BOARD_BYID"    # stable /dev/serial/by-id/... path
#
# The board.conf file is generated by detect_arduino.sh.  It is intentionally
# shell-sourceable (KEY="VALUE" lines) so the same file feeds bash scripts,
# Python (via board_conf.py), and systemd EnvironmentFile= directives without
# any format conversion.

INNO_BOARD_CONF="${INNO_BOARD_CONF:-/var/lib/inno-pilot/board.conf}"

load_board_conf() {
    if [[ ! -f "$INNO_BOARD_CONF" ]]; then
        echo "ERROR: board config $INNO_BOARD_CONF missing — run detect_arduino.sh" >&2
        return 1
    fi
    # shellcheck disable=SC1090
    source "$INNO_BOARD_CONF"
    # Required fields — fail loudly if board.conf is partial/corrupt
    : "${INNO_BOARD_FQBN:?board.conf missing INNO_BOARD_FQBN}"
    : "${INNO_BOARD_PORT:?board.conf missing INNO_BOARD_PORT}"
    : "${INNO_BOARD_BYID:?board.conf missing INNO_BOARD_BYID}"
    : "${INNO_BOARD_BAUD:?board.conf missing INNO_BOARD_BAUD}"
    # Derive BYID_REAL if not present (older board.conf files)
    : "${INNO_BOARD_BYID_REAL:=${INNO_BOARD_BYID}.real}"
    # Default build flags if absent — preserves existing behaviour for callers
    : "${INNO_BOARD_BUILD_FLAGS:=build.extra_flags=-DSERIAL_RX_BUFFER_SIZE=128}"
    return 0
}

# When sourced with `--print` argument, dump the loaded values for debugging:
#   bash board_conf.sh --print
if [[ "${BASH_SOURCE[0]}" == "${0}" ]] && [[ "${1:-}" == "--print" ]]; then
    if load_board_conf; then
        echo "INNO_BOARD_FQBN=$INNO_BOARD_FQBN"
        echo "INNO_BOARD_VARIANT=${INNO_BOARD_VARIANT:-unknown}"
        echo "INNO_BOARD_PORT=$INNO_BOARD_PORT"
        echo "INNO_BOARD_BYID=$INNO_BOARD_BYID"
        echo "INNO_BOARD_BYID_REAL=$INNO_BOARD_BYID_REAL"
        echo "INNO_BOARD_BAUD=$INNO_BOARD_BAUD"
        echo "INNO_BOARD_BUILD_FLAGS=$INNO_BOARD_BUILD_FLAGS"
        echo "INNO_BOARD_DETECTED_AT=${INNO_BOARD_DETECTED_AT:-unknown}"
        echo "INNO_BOARD_DETECT_METHOD=${INNO_BOARD_DETECT_METHOD:-unknown}"
    fi
fi
